define angelika_speech_text = [
"{color=#8B0A50}- Gaudete! I am Mistress Angelika. The council of Guild Masters has given me the honor to train and certify beginners. What is your name?{/color}",
"{color=#191970}- My name is {b}[mc]{/b}. I have long dreamed about this moment.{/color}",
"{color=#000000}Mistress Angelika checks the list and nods.{/color}\n{color=#8B0A50}- It indicates here that you have already fully paid the entry fee, {b}[mc]{/b}. Good. But consider this: we will not tolerate black sheep in our guild, no matter how much they pay. The honor of our organization is paramount.{/color}",
"{color=#8B0A50}- In order to become a full member of the Slavers Guild you'll have to pass the exam in conditions close to practice. We also provide training for beginners. I will tell you everything I know a hundred times if need be.{/color}",
""
]
define attitude_text = {
    "cold":         ["   Attitude: cold"],
    "haughty":      ["   Attitude: haughty"],
    "polite":       ["   Attitude: polite"],
    "unkind":       ["   Attitude: unkind"],
    "fastidious":   ["   Attitude: fastidious"],
    "cautious":     ["   Attitude: cautious"],
    "friendly":     ["   Attitude: friendly"],
    "protective":   ["   Attitude: protective"],
    "obsequious":   ["   Attitude: obsequious"]
}
define tutorial_lectureGIGA ={
    "tutorial_lecture1": [
    "Slave rating is affected by various factors. Firstly, it is the sum of her skills. The ability to keep the house, entertain her master and sexual techniques - all increase her rating.",
    "Another important factor is her obedience. A perfect slave should thoroughly fulfill all the rules and obey any request of her master without hesitation and delay. Most valued is the sincere desire to please and serve.",
    "Also of considerable importance is the mental state of a slave. On one hand she should not be squeamish or haughty, but on the other it is good when the girl is temperamental and has a strong character. People don't usually like nondescript dolls. People are drawn to bright personalities.",
    "Finally, charm has a very significant influence on her rating. The extent to which the slave is able to show herself and if she looks stylish. At the same level of skill, a stylish slave will always please the customer more than a dull one. It is necessary to take this into account when selling slaves to elite customers.",
    "If your training leaves scars on her body, her charm will inevitably fall. Be careful and measure force. It is also necessary to track the weight and physical condition of the girl. She should be neither too thin nor too thick. Stamina and health is very important."
    "A client is likely to refuse to buy a poorly presented slave, and might refuse to buy that slave even if you fix their appearance. It is necessary to take into account the vagaries of customers.",
    "It should also be remembered that this applies only to the general case. Each customer may have their own requirements, which strongly change the rating of our goods in his eyes.",
    "If a client acquires a gladiatrix from you, her strength and exoticism will be important, but her housekeeping and cooking skills won't matter. In the future, you will have to select untrained slaves and train them based on a specific customer's wishes.",
    "Since the Slavers Guild is the customer for the examination, we will only take into account her overall rating. Her individual skills won't matter as long as her overall rating is high enough.",
    ""
    ],
    "tutorial_lecture2": [
    "A rebellious slave is a complete punishment for the master. One of the most important tasks of any trainer is unquestioned obedience. This is the only way that you can do further training effectively and get a decent rating.",
    "The slave's willingness to obey depends on a variety of factors. It is important to know all of them and understand how positive factors can be produced and maintained. Listen carefully.",
    "The first thing that comes to mind: {color=#960018}fear{/color}. You can do anything you want with a slave. In most cases it will not be difficult to intimidate her using pain, abuse and violence. We were able to calculate that the average motivation of {color=#960018}fear{/color} is almost twice as strong as any other.",
    "It should however be remembered that {color=#960018}fear{/color} has its pitfalls. Firstly, you have to be careful with punishments, so as not to cause irreparable physical harm to the girl. But even more important is not to damage her mind.",
    "Whenever you punish a slave, she will not only start to fear you, but her dissatisfaction will also grow. This is a direct way to drive a slave into a deep depression. Without positive motivation, training a slave will be very difficult because her distress and self-pity will stop the girl from focusing on her training.",
    "Besides lowering her mood, {color=#960018}fear{/color} has an additional dark side. We call it {color=#464451}despair{/color}: a destructive terror emanating from a misunderstanding and rejection of fear. If a slave gets punished without feeling guilt, or if the intensity of punishment exceeds the degree of guilt she feels - her {color=#464451}despair{/color} inevitably grows.",
    "A sensitive girl may fall into {color=#464451}despair{/color} simply because of her bad mood. When a slave is extremely gentle, sadness will lead her to depression faster. Whenever you consider punishing your slave, do not only consider the degree of her guilt, but also her sensitivity.",
    "{color=#464451}Despair{/color} destroys personality. Under its influence a slave begins to lose her temperament and self-confidence, gradually breaking her will. In the early stages it can help, but in the end it will only lower her rating. Be careful.",
    "To get rid of {color=#464451}despair{/color}, try to ensure that your slave is elated. Satisfied girls will gradually forget their {color=#464451}despair{/color}. Rewarding her with time for herself can help also. In addition, with a good mood it will be much easier to learn new material and she will concentrate more during training.",
    "At the same time, a slave that is satisfied with life will quickly forget about her {color=#960018}fear{/color}, meaning that you will have to develop other sources of respect so that she obeys you. Namely: {color=#082567}habit{/color}, {color=#CD9B1D}taming{/color}, {color=#B452CD}awareness{/color} and {color=#00a86b}devotion{/color}.",
    "Let's start with {color=#082567}habit{/color}. It is no secret that people can obey orders just because they are used to doing it. Every time a slave obeys your instructions and rules, her {color=#082567}habit{/color} of slavery slightly increases. Gradually, the slave will just forget that she once was free.",
    "While boosting the development of {color=#082567}habitual obedience{/color} is difficult, try to be strict towards your slave; it will speed up the process. A proud personality will develop {color=#082567}habit{/color} slowly, but {color=#082567}habit{/color} will also gradually make them lose their pride. The same is true for humiliation, of course.",
    "A good foundation for obedience is what we call {color=#B452CD}awareness{/color} - a rational understanding of the slave's position. Try to explain to the slave that loyalty will be rewarded, and that resistance will lead to inevitable punishment. {color=#B452CD}Awareness{/color} promotes obedience, but a strong will and pride can interfere with accepting her fate.",
    "{color=#B452CD}Awareness{/color} can be achieved not only by direct subordination, but also through reasonable rewards. By rewarding a slave, you do not just improve her mood, you also make her realize that obedient behavior leads to good treatment.",
    "Be extremely careful though. Rewarding a slave beyond her merits can make her {color=#EE1289}spoiled{/color}. A spoiled slave is less controllable and will always require some kind of positive incentive. Otherwise, she will start to get upset and fall into {color=#464451}despair{/color}. To correct this, you must not hesitate to put her in her place. Do not reward every act of compliance, as this also leads to {color=#EE1289}spoiling{/color}. It is best to give rewards no more than once or twice each day.",
    "In addition to {color=#B452CD}awareness{/color}, there is also {color=#CD9B1D}taming{/color} - instinctive obedience, when your slave subconsciously feels your superiority and strives to please you. Weak-willed people are more prone to this type of obedience.",
    "To develop a slave's {color=#CD9B1D}taming{/color} you can use rules, punishments, restrictive clothing and heavy piercings. When non-compliance causes pain or deprivation and the slave is constantly reminded of her place, obedience will become a reflex. Another way to develop {color=#CD9B1D}taming{/color} is exploiting sexual desire. People are subconsciously drawn to the source of pleasure.",
    "While punishing a slave beyond her understanding causes {color=#464451}despair{/color}, if you punish her too lightly, she may grow {color=#EE1289}spoiled{/color}. If you neglect to punish her and she disobeys you again, her {color=#CD9B1D}taming{/color} will inevitably weaken. But if you give her a new task, and she performs it diligently, her feeling of merit will reduce her guilt. While it is best not to let a guilty slave sleep unpunished, if she is frightened a respite may lift her spirits.",
    "The final goal of raising her obedience is to make her accept slave morality. When a slave accepts her position with all of her heart and sincerely wants to serve her master, she has reached a moral growth that we call {color=#00a86b}devotion{/color}. This source of loyalty is doubly valuable because it is the most reliable and will motivate her to do her best even after she is sold to a new owner.",
    "{color=#00a86b}Devotion{/color} begins to appear when on one hand the slave is satisfied with her position and is in a good mood, and on the other she has developed habitual as well as instinctual and rational obedience. Be mindful that it is difficult to develop {color=#00a86b}devotion{/color} in a slave who is arrogant or {color=#960018}terrified{/color} of you. To strengthen her loyalty, you can also reward her with companionship and intimacy.",
    "Acknowledged whip masters are able to sharply raise their slave's {color=#00a86b}devotion{/color} through catharsis: a special state of enlightenment, the moment of truth, comes in the second of highest pain or pleasure. But this technique is only for the best.",
    "Summing up, we can isolate some simple rules of training: punish your slave for misdeeds, matching the intensity of punishment to the guilt she feels. Reward your slave for good behavior, but only on merit and not too often. If she does not {color=#960018}fear{/color} you, give her at least three rules to follow so she starts to develop her {color=#082567}habit{/color} and does not become {color=#EE1289}spoiled{/color}. Control her orgasms and keep watch over her mood.",
    "I will now say a few words about superiority and physical resistance. It will be much easier to subdue the girl who initially feels that you are stronger and. On the other hand, if she feels that she is stronger than you, she will not want to obey.",
    "Whether or not she will feel your superiority is influenced by several factors. First - of course - your physical strength. Second - your spiritual strength and charisma. Third - the experience of command, the ability to dominate. Finally - your appearance. Good looks make it easier to submit to you.",
    "But the slave's personal qualities are also important. A strong character, high emotionality and, of course, the slave's pride will prevent her from feeling your superiority. Also, watch out if she does feel smarter than you, thinking that she can outwit you. She will be less inclined to obey.",
    "If your superiority is low, she might put up a fight. In response to your attempts to punish or rape her, your slave will defend herself by force. If she can beat you, the consequences can be dire. But your victory will confirm your superiority.",
    "Superiority alone, even if very high, does not guarantee your orders will be followed, but it accelerates the development of obedience and reduces the likelihood of physical confrontation. Keep yourself in good physical shape, develop a commanding voice and keep a good physical appearance.",
    ""
    ],
    "tutorial_lecture3": [
    "Let's talk more about punishments and rewards. In the second lecture we talked about {color=#464451}despair{/color} and {color=#EE1289}spoiling{/color}, but I will repeat myself. Punishing a slave too much - we feed {color=#464451}despair{/color}. Rewarding her with something she does not deserve - we pamper and {color=#EE1289}spoil{/color} the slave, although it improves her mood.",
    "It is important to understand the key point: the merits and sins of the slave differ from case to case. You should understand what made her act in a certain way.",
    "Suppose that you take an innocent girl that is not accustomed to mistreatment and tell her to mate with a tribal bull for your entertainment. In her eyes, refusing to do that is not a serious offense, as your demand is far above what she is willing to do.",
    "If you brutally punish the girl for disobeying such an order, it will inevitably lead to {color=#464451}despair{/color}, as she does not understand why the rejection of such a vile act can be regarded as something impermissible. But over time, things will change.",
    "If your slave is already trained and rather obedient, she will actually realize her sin. Rejection of the same action with a bull from the already prepared girl should cause a much more severe reaction from you.",
    "Same story with the rewards. Do not only evaluate the result, but keep the slave's personality in mind. Suppose your nearly untrained slave has agreed to a lesson on deep throating. Even if the result is not perfect, she agreed to do it and overcame her resistance. She should be rewarded properly.",
    "On the contrary, if a slave is doing something very well because she already knows how to do it, and it is completely effortless - she does not deserve a reward. You may even consider punishing her.",
    "Always evaluate the slave's merits and sins on a five-point system. And also evaluate the power of rewards and punishments. Always keep in mind: she gets what she deserves.",
    "But remember that what I said is for general guidance only. There are cases when it makes sense to punish or reward the slave more than she deserves, even at the risk of {color=#464451}despair{/color} or {color=#EE1289}spoiling{/color} her. Decisions are always made by you. Use your experience and intuition.",
    "Let's move on to the specific types and forms of rewards and punishments. Any impact derives its strength from the slave's specific desires and fears.",
    "Punishments are based on pain, feelings of helplessness, disgust, shame, psychological vulnerability, phobias of blood, darkness, spiders, water, fire and other things.",
    "Rewards may be based on the need for approval, desire for comfort, a passion for luxury, sexual pleasure or even food if she has a sweet tooth.",
    "Each slave has her own strengths and weaknesses, her passions and phobias. Learn what she wants and what she is afraid of, and then use it for your own purposes - it is the key to gaining control over a slave rapidly.",
    "Imagine that you have to train a fearless, battle-hardened warrior. Surely you will not be able to break her will by flogging or with the sight of blood. But you can try to put pressure on her psychologically or tie her up so that she feels helpless in front of you.",
    "Do not forget that a person gets used to everything. Resistance develops to the types of exposure, and to specific methods of punishment and reward. Exceptions are only the slave's innate phobias and passions. As for the rest, be creative and try not to repeat the same methods too often. In all forms of training, remember: variety is best.",
    "Verbal rewards and punishments have one very significant advantage: they do not take a lot of time and effort, neither yours nor your slave's. However, this is all the upsides this method has. Praising and swearing quickly lose strength, as well as threats and promises if you don't act on them.",
    "You can punish a slave on the spot without any available tools. It's quick and practical, but remember that tools increase the efficiency of punishments. In addition, beatings can leave bruises on the girl. Gradually, the wounds will heal, but even the traces will reduce her rating and charm.",
    "To inflict pain, try to use at least a minimum amount of tools. For spanking, in ascending order: slippers, belt, cane, lash and whip. Be careful when using either lash or whip, as the scars may remain forever. A lot depends on your skill. If you make a mistake, there is always the medical center.",
    "A great advantage of binding your slave is that it means less effort. You punish your slave with arbitrarily long torment. Nevertheless, bondage on average is slightly less effective than physical punishment of the same level.",
    "If your slave is aroused - reward her by caressing her. She will not lose energy herself, moreover, a good massage can even energize her more. But keep in mind that her arousal will only go down if she cums. Otherwise you will just raise her arousal even more. Also be mindful of your rules if you deny her orgasms.",
    "To save your own energy, you can reward your slave with free time. If you just give her a rest, you may be able to use her remaining energy tomorrow. But your slave will be even more joyful if you give her the opportunity to have fun and play games.",
    "If you have some extra sparks and you are not afraid that your slave may gain weight, you can reward her with sweets. Rare dishes can be very expensive, but even they can become boring if eaten many times in a row. When you reward a slave with sweets, try to add variety.",
    "Some punishments may require special equipment or facilities. For the examination, we do not provide torture tools and units, so you will have to manage with the minimum.",
    "For some rewards it may be necessary to take the slave out into the city. During examination training, you must not leave the walls of the guild, so those types of rewards will not be available. Nevertheless, we are confident that you will have enough opportunities for training.",
    ""
    ],
    "tutorial_lecture4": [
    "During training, you will have to watch out for a number of domestic issues. For this very reason, the majority of slavers acquire a personal assistant, oftentimes one of their slaves. Assistants can help with the housework, entertain you, keep track of your slaves and pass on skills to them.",
    "The Guild does not provide assistants for the exam, so you will have to manage on your own. Of course, you can use the slave for housekeeping, if she is sufficiently obedient and has the necessary skills.",
    "The first thing to remember is your personal and the slave's hygiene. Dirt contributes to disease and reduces mood. In addition, a dirty slave receives greater damage from fights and tortures, as injuries might get infected.",
    "Dirt accumulates over time and from many activities, especially those related to working, cleaning, cooking or dirty sex. To maintain hygiene, you should occasionally wash yourself. If you do not have a private bathroom in your home, you will have to go to the onsen at the hot spring, the beach or the spa.",
    "The Guild has a bathroom attached to the examination area, so you do not need to go into the city. You can bathe alone or together with the slave. In the second case, only she will spend her energy, but will wash you both. In addition, this should elevate your mood.",
    "Your home also gets dirty. Gradually it accumulates dust and dirt, stale clothes, dirty dishes and so on. Do not forget to carry out regular cleaning so as not to reduce the mood of all the inhabitants of the house. And remember, the bigger the mess at hand - the more difficult it will be to clean up.",
    "Homemade food can greatly improve your own mood and your slave's mood as well. However, its preparation requires time and effort. If you do not want to cook, you can get canned food and semi-finished goods.",
    "Watch the weight of your slave. You should ensure that she is neither too fat nor too starved. Choose portions of food so that the weight of your slave remains stable, unless you are trying to change her.",
    "An important thing is the personal characteristics of metabolism. A slave with a good metabolism is capable to absorb about twice as many calories as normal without harm and will gain more stamina from her meals, at least until she is healthy. A girl with a weak metabolism will quickly gain excess weight and it will be difficult for her to lose weight.",
    "Especially for a slave who lacks endurance, but even for the most capable, remember that she can damage herself if she over-works her muscles. Be mindful of her limits when commanding your slave to do something that is physically demanding. If she seems less energetic than usual, it may be necessary to adjust your plans.",
    "If you are not a born cook or butler, doing housework will be a heavy burden on your mood. However, until you have an assistant, you sometimes will need to do it yourself. Giving this task to a slave may not be productive, especially if she lacks skill or does not have enough energy. On the contrary, doing housework is a simple task that even a disobedient slave might not refuse, so it can be a good place to start in building positive habits.",
    ""
    ],
    "tutorial_lecture5": [
    "{color=#191970}- And what kind of exam, Mistress?{/color}",
    "{color=#8B0A50}- The task is to train a slave for sale. We will give you the basic premise, a choice of slaves, a set of clothes, a full refrigerator and funding in the amount of eight hundred sparks. You'll have to pay the rent and feed your slave.{/color}",
    "{color=#8B0A50}- These sparks will last about a month. More or less depending on your frugality. Anyway, during this time you will have to raise the rating of your slave at least to {b}C+{/b} rank.{/color}",
    "{color=#8B0A50}- If by the time you run out of sparks the girl has a bad rating - you failed your exam. If your slave dies - you failed the exam too. Do you get it?{/color}",
    "{color=#191970}- Completely. That does not sound too difficult.{/color}",
    "{color=#8B0A50}- Excellent. Self-confidence - already half of the work. The most important quality for a person of our profession. All that is left to do is show that you are able to do it yourself. You can start right now or continue training until you feel ready.{/color}",
    ""
    ]
}
define demo_girl_text = ["Former housewife who was sold into slavery by the bank, for the debts of her husband. She served as a «specialist in entertainment» for the managers of a corporation, so she has some required experience. But she is not specially trained.\n{color=#009900}Difficulty: minimal{/color}",
                        "Lesbian amazon from the savage space tribe. She has great makings, but do not forget that this girl has great physical strength, fighting skills, and she despises men.\n{color=#6B0084}Difficulty: normal{/color}",
                        "Little princess of a small kingdom of a highly-magical world. The combination of poor health, vulnerability and prohibitive defiance will make her training especially challenging. But her beauty is worth it.\n{color=#cd0000}Difficulty: high{/color}"

]
